### ISSUE TITLE
Build failure in atlas related to codec header

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/eckit#114]
### What happened?

I tried to build atlas develop with eckit develop and got this failure:

In file included from /home/h01/frwd/cylc-run/mi-be984/share/installs/eckit-gnu/include/eckit/codec/codec.h:30,
                 from /home/h01/frwd/cylc-run/mi-be984/work/1/git_clone_atlas/atlas/atlas_io/eckit_codec_adaptor/src/atlas_io/atlas-io.h:13,
                 from /home/h01/frwd/cylc-run/mi-be984/work/1/git_clone_atlas/atlas/atlas_io/tests/test_io_encoding.cc:14:
/home/h01/frwd/cylc-run/mi-be984/share/installs/eckit-gnu/include/eckit/codec/detail/StaticAssert.h:15:10: fatal error: eckit/codec/eckit_codec_config.h: No such file or directory
   15 | #include "eckit/codec/eckit_codec_config.h"

### What are the steps to reproduce the bug?

Build atlas and eckit develops.

### Version

develop

### Platform (OS and architecture)

not relevant

### Organisation

Meto

**Comment by pmaciel** [comment]
This has been resolved with [this commit](https://github.com/ecmwf/eckit/commit/1aaa747c27197d155bf6afd488e29bb4fb6a08f7) -- thanks!
