### ISSUE TITLE
Compilation failure for eckit_test_mpi_objserialisation.cc => solved

### ISSUE THREAD

**Issue by benjaminmenetrier** [ecmwf/eckit#12]
Hello,

I had an error message when compiling eckit:

[ 83%] Building CXX object tests/mpi/CMakeFiles/eckit_test_mpi_objserialisation.dir/eckit_test_mpi_objserialisation.cc.o
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:167:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<Obj> next_;
          ^~~~~~~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc: In constructor ‘eckit::test::Obj::Obj(eckit::Stream&)’:
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:87:13: error: ‘next_’ was not declared in this scope
             next_.reset(new Obj(s));
             ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:87:13: note: suggested alternative: ‘next’
             next_.reset(new Obj(s));
             ^~~~~
             next
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc: In member function ‘void eckit::test::Obj::encode(eckit::Stream&) const’:
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:98:12: error: ‘next_’ was not declared in this scope
         if(next_) {
            ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc: In member function ‘void eckit::test::Obj::add(eckit::test::Obj*)’:
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:106:13: error: ‘next_’ was not declared in this scope
         if(!next_) {
             ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:110:9: error: ‘next_’ was not declared in this scope
         next_->add(o);
         ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc: In lambda function:
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:123:20: error: ‘next_’ was not declared in this scope
             if(not next_ && not rhs.next_) {
                    ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:123:37: error: ‘const class eckit::test::Obj’ has no member named ‘next_’
             if(not next_ && not rhs.next_) {
                                     ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:126:16: error: ‘next_’ was not declared in this scope
             if(next_ && rhs.next_) {
                ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:126:29: error: ‘const class eckit::test::Obj’ has no member named ‘next_’
             if(next_ && rhs.next_) {
                             ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:127:39: error: ‘const class eckit::test::Obj’ has no member named ‘next_’
                 return *next_ == *rhs.next_;
                                       ^~~~~
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc: In member function ‘void eckit::test::Obj::print(std::ostream&) const’:
${code}/eckit/tests/mpi/eckit_test_mpi_objserialisation.cc:150:12: error: ‘next_’ was not declared in this scope
         if(next_)
            ^~~~~

Adding the include "#include <memory>" at the top of eckit/tests/mpi/eckit_test_mpi_objserialisation.cc solved the issue.

Benjamin

**Comment by wdeconinck** [comment]
Dear @benjaminmenetrier  I also had seen this error and had already fixed it in our eckit fork. I personally don't have permission to push this to this github repo. Waiting for @tlmquintino  for this.

**Comment by tlmquintino** [comment]
I've now pushed this fix in.
