### ISSUE TITLE
Travis-ci build is failing on AMD64

### ISSUE THREAD

**Issue by sanjaymsh** [ecmwf/eckit#34]
Hi,

I am trying to enable ppc64le build on travis-ci, But its failing on AMD64 itself with the error below:

"$ cmake -DCMAKE_MODULE_PATH=${ECBUILD_MODULE_PATH} ${ECKIT_CMAKE_OPTIONS} ${ECKIT_SOURCE_DIR}
CMake Error at CMakeLists.txt:11 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version 3.10.2
-- Configuring incomplete, errors occurred!
The command "cmake -DCMAKE_MODULE_PATH=${ECBUILD_MODULE_PATH} ${ECKIT_CMAKE_OPTIONS} ${ECKIT_SOURCE_DIR}" exited with 1.
0.01s$ make -j4
make: *** No targets specified and no makefile found.  Stop.
The command "make -j4" exited with 2.
0.00s$ bin/eckit-version
/home/travis/.travis/functions: line 109: bin/eckit-version: No such file or directory
The command "bin/eckit-version" exited with 127.
0.01s$ ctest
*********************************
No test configuration file found!" 

Full error log can be tracked here : https://travis-ci.com/github/sanjaymsh/eckit/builds/188376660
Please have a look on this.
Thanks !!

**Comment by sanjaymsh** [comment]
Even i tried to update the 'cmake' from .travis.yml file like below:

 # CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
    CMAKE_URL="https://cmake.org/files/v3.18/cmake-3.18.3-Linux-x86_64.tar.gz"

But same error was observed.

**Comment by wdeconinck** [comment]
Hi @sanjaymsh, thanks for bringing this to our attention.
The commit 3a18002 just added in the develop branch should fix the Travis-CI for now.

**Comment by sanjaymsh** [comment]
Thanks !!

**Comment by sanjaymsh** [comment]
Hi @wdeconinck , Can you please help me to add the ppc64le in this project?
I am trying to add it, but it failing on ppc64le due to 'cmake'. I am trying to install cmake for ppc64 via 'snap' but no use.
Please see the log here : https://travis-ci.com/github/sanjaymsh/eckit/builds/188680894

**Comment by wdeconinck** [comment]
Hi @sanjaymsh develop branch now has support for `ppc64le`.
I could also not get snap to work. It seems to be currently broken for the ppc64le travis images.
I resorted to building cmake from source (it is cached for subsequent builds of same branch)

**Comment by sanjaymsh** [comment]
Hi @wdeconinck Thanks for adding it, i was struggling for that !!
