### ISSUE TITLE
an initialized argv issue in Parallel.cc 

### ISSUE THREAD

**Issue by TingLei-NOAA** [ecmwf/eckit#37]
Dear Mr. or Mrs.,
When I ran a JEDI application, built with debug compiling option,  which includes eckit , I got an error message pointing to one line in parallel.cc (line 247 in my version)
^
MPI_CALL(MPI_Init_thread(&argc, &argv, required, &provided));
V 
It said argv was not initialized, which should be initialized when 
^^
 if (eckit::Main::ready())
...
 argv = eckit::Main::instance().argv();
.....
V
So, seems the eckit is not ready yet.  So, any clues/suggestions what I can do for this.
Your help is appreciated

**Comment by wdeconinck** [comment]
Hi @TingLei-NOAA 
Somehow you are  using a `eckit::MPI` call before following has been called:
```
eckit::Main::initialize(argc,argv);
```
I cannot tell you why because this must be in your own software stack.

**Comment by tlmquintino** [comment]
@TingLei-NOAA can you please confirm this is solved now?

**Comment by TingLei-NOAA** [comment]
Hi, Tiago,
This issue can be closed now.
Thanks.
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624
