### ISSUE TITLE
Error with ecbuild (CRITICAL - Please define a version for eckit)

### ISSUE THREAD

**Issue by chengdang** [ecmwf/eckit#39]
Hello Sir/Madam:

I'm trying to build eckit on MacOS, here is the Error message I got:

```
> ecbuild ..
Found CMake version 3.20.2

cmake -DCMAKE_MODULE_PATH=/usr/local/share/ecbuild/cmake ..

-- ecbuild   3.6.2	/usr/local/share/ecbuild/cmake
-- cmake     3.20.2	/usr/local/Cellar/cmake/3.20.2/bin/cmake
-- ---------------------------------------------------------
-- Added C flag [-pipe]
-- Added CXX flag [-pipe]
-- ---------------------------------------------------------
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  CRITICAL - Please define a version for eckit

  	project( eckit VERSION x.x.x LANGUAGES C CXX Fortran )
Call Stack (most recent call first):
  /usr/local/share/ecbuild/cmake/ecbuild_declare_project.cmake:103 (ecbuild_critical)
  CMakeLists.txt:13 (ecbuild_declare_project)


-- Configuring incomplete, errors occurred!
See also "/Users/dangch/Documents/jedi/projects/eckit/build/CMakeFiles/CMakeOutput.log".
See also "/Users/dangch/Documents/jedi/projects/eckit/build/CMakeFiles/CMakeError.log".
```

Here is my system configuration:
```
HOMEBREW_VERSION: 3.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92cf9047191393a2d624c64fc28d9595309ba273
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1837d0c34a85a96692f3b55619df90562a51f096
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5

ecbuild version 3.6.2
cmake version 3.20.2
```

Could you please instruct me on how to set the eckit version? I'm using the code branch 0.24.1, while I'm not sure if this is the appropriate version for macOS 11.

**Comment by oiffrig** [comment]
Hi @chengdang,

0.24.1 is a very old version of eckit, and therefore not compatible with ecbuild 3.6.2. I would strongly recommend using a more recent version if you can. The "latest release" label on 0.24.0 is wrong, we are looking into it, there have been many releases after that.

**Comment by chengdang** [comment]
@oiffrig Thank you! That is good to know. 
I just tried branch ` 2021.03.0`, and it seems to be working fine. 
Thanks.

**Comment by cesarmagnosjr** [comment]
Dear @chengdang 

Where in the project do I put this?
It's a function I call with

$ ecbuild project...

or do i define the project somewhere?

Regards.
César Magno.

**Comment by chengdang** [comment]
Hello @cesarmagnosjr :
please refer to this file: https://github.com/JCSDA/crtm-bundle/blob/5a1be75977e0ed3db0ee8f591696e8fdfbc8e78d/CMakeLists.txt

Is this the code repository you are testing?

**Comment by oiffrig** [comment]
Hi @cesarmagnosjr, @chengdang,

I believe this issue has nothing to do with eckit. You may want to open another issue in a more relevant repository, like crtm-bundle.

**Comment by chengdang** [comment]
@oiffrig Yes indeed. 
@cesarmagnosjr please open another issue on https://github.com/JCSDA/crtm-bundle for more discussion.

**Comment by cesarmagnosjr** [comment]
Dear colleagues, good morning.

I ended up contacting the code developer who helped me with some details. At first this problem is solved with a 'git pull', however, other small problems appeared that he is looking into.

If I need it, I will open a new ticket.
Thank you very much for your attention.

Regards!

**Comment by cesarmagnosjr** [comment]
Dear colleagues, good morning.

I ended up contacting the code developer who helped me with some details. At first this problem is solved with a 'git pull', however, other small problems appeared that he is looking into.

If I need it, I will open a new ticket.
Thank you very much for your attention.
