### ISSUE TITLE
ISSUE ON INSTALLING eckit-1.20.0.tar.gz

### ISSUE THREAD

**Issue by Darivo-cmd** [ecmwf/eckit#45]
Hi!
I'm trying to install the eckit (required packages by other program) version 1.20.0 but encouter the following problem.
I have ecbuild correctly installed (I think > darivo@Rivo:~/eckit-1.20.0/build$ which ecbuild _**give**_ /opt/cdo-install/bin/ecbuild
But when I enter this ~/eckit-1.20.0/build$ ecbuild --prefix=$installdir ../ to install eckit, it requires root permission. So I try with sudo but unfortinately it says ecbuild not found. 
:~/eckit-1.20.0/build$ sudo ecbuild --prefix=$installdir ../
_**sudo: ecbuild: command not found**_
A help is most wellcome! Thanks inadvance. 
For info, I downloaded tarball from here (github)

**Comment by wdeconinck** [comment]
Hello @Darivo-cmd,
You don't necessarily need to have an installed ecbuild as it works from source.
Try this:
```
git clone https://github.com/ecmwf/ecbuild
export ecbuild_ROOT=$PWD/ecbuild
```
and then use
```
${ecbuild_ROOT}/bin/ecbuild --prefix=$installdir ../
```
or simply
```
cmake -DCMAKE_INSTALL_PREFIX=$installdir ../
```
The latter will work as well because `ecbuild_ROOT` is exported in environment.

**Comment by Darivo-cmd** [comment]
Hi Willem,
That works well. Thanks a lot!


*Best regards,*=============
*Rivo RANDRIANARISON*
*Meteorologist in Charge  & **Lead Forecaster*
*Topics : *
- Extreme Weather Monitoring / Forecasting
- Climate Monitoring

DIRECTION GÉNÉRALE DE LA MÉTÉOROLOGIE
Rue FARAFATY
BP : 1254 Ampandrianomby,
Antananarivo (101), MADAGASCAR

Tel : +261 (0) 34 05 561 05
E-mail : ***@***.*** | ***@***.***
Skype ID : rivo.mto
Siteweb : www.meteomadagascar.mg


*" Early Warning and Early Action **(WMD 2022)*
*"************************************************************



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Darivo-cmd** [comment]
Hi Willem,
That works well. Thanks a lot!
