### ISSUE TITLE
eckit installation of Cray environments

### ISSUE THREAD

**Issue by devarajun** [ecmwf/eckit#49]
eckit build is successful on cray environment. However, when I try to build FDB, I get an error message related to eckit file missing. 
It looks like there is no cmd folder in my eckit installation directory. Do you know why cmd folder is not found even though while installing eckit no error found.

See the error message below:

/project/devaraju/fdb/src/fdb5/remote/fdb-monitor.cc:16:10: fatal error: eckit/cmd/CmdApplication.h: No such file or directory
   16 | #include "eckit/cmd/CmdApplication.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by tlmquintino** [comment]
When building the fdb remote, you need the eckit cmd optional component to be built. 
What options have you used to build eckit?

**Comment by devarajun** [comment]
I have now tried: 

cmake ../ -DCMAKE_INSTALL_PREFIX=$installdir -DENABLE_ECKIT_CMD=ON -DENABLE_MPI=ON

But I get the following error:

could you please let me know how to install package curses?  Thank you!
 

CMake Error at /project/project_462000007/devaraju/EasyBuild/SW/LUMI-22.08/C/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  CRITICAL - Feature ECKIT_CMD cannot be enabled -- following required
  packages weren't found: Curses

**Comment by devarajun** [comment]
Okay, I have installed successfully eckit with cmd ON.  Thanks for your help @tlmquintino  I am closing the issue now.
