### ISSUE TITLE
Need of MPI_Sendrecv_replace interfaces

### ISSUE THREAD

**Issue by andreapiacentini** [ecmwf/eckit#53]
We (Benjamin Ménétrier and myself) are trying to optimize a 4D localization in JEDI-OOPS, based on an open-end shift.  We miss an eckit interface to MPI_Sendrecv_replace. In order to implement open-end shifts, we also need a method to expose the `MPI_PROC_NULL` constant.  
Thank you.

**Comment by wdeconinck** [comment]
This has been solved with #57
