### ISSUE TITLE
Encountered error during compilation with nvhpc22.1 

### ISSUE THREAD

**Issue by yangjinhui11** [ecmwf/eckit#77]
### What happened?

When I compile the eckit with nvhpc22.1 compiler. I met errors like follows:
CMakeFiles/eckit_info.dir/eckit-info.cc.o: In function `EckitInfo::EckitInfo(int, char**)':
/PathofEckit/eckit/src/tools/eckit-info.cc:38: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/eckit_info.dir/eckit-info.cc.o: In function `EckitInfo::~EckitInfo()':
/PathofEckit/eckit/src/tools/eckit-info.cc:45: undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/eckit_info.dir/eckit-info.cc.o: In function `eckit::option::SimpleOption<bool>::~SimpleOption()':
/PathofEckit/eckit/src/tools/eckit/src/eckit/option/SimpleOption.cc:57: undefined reference to `operator delete(void*, unsigned long)'
../../lib/libeckit.so: undefined reference to `operator delete[](void*, unsigned long)'

### What are the steps to reproduce the bug?

using nvhpc 22.1 compiler

### Version

the newest version

### Platform (OS and architecture)

Linux ln01 3.10.0-1160.31.1.el7.x86_64

**Comment by wdeconinck** [comment]
@yangjinhui11 thank you for this report. We have been compiling eckit with this compiler now without problem. Could you verify it is still the case with latest eckit version?

**Comment by wdeconinck** [comment]
Issue gone stale... Please reopen if this is still a problem.
