### ISSUE TITLE
Definition of eckit::offset:dump(DumpLoad&) missing

### ISSUE THREAD

**Issue by gesalous** [ecmwf/eckit#84]
### What happened?

I am using the develop branch and have encountered an issue that I hope you might be able to provide clarity on.

I attempted to use the eckit::offset::dump(DumpLoad&) member function in my program. Upon doing so, I observed a linker error. Upon closer examination, I found that while the declaration of the said member function is present in the library, its corresponding definition appears to be absent.

May I kindly inquire if this omission is intentional? Your insights on this matter will greatly benefit me as it will aid in my understanding and utilization of the eckit library.

### What are the steps to reproduce the bug?

Write and link a program that tries to use eckit::offset:dump member function.

### Version

develop branch

### Platform (OS and architecture)

Arch OS x86_64

### Organisation

FORTH

**Comment by wdeconinck** [comment]
@danovaro any progress on this to report yet?

**Comment by danovaro** [comment]
sorry for taking so long. Fix just pushed
